application: myplancount
version: 1
runtime: python27
api_version: 1
threadsafe: true

# Handlers match in order, put above the default handler.
handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
  login: required

- url: /static
  static_dir: static
  login: required

- url: /s/.*
  script: main.app
  login: required

- url: /g/.*
  script: main.app
  login: required

- url: /docs-authorization
  script: main.app
  login: required

libraries:
- name: webapp2
  version: latest
- name: pycrypto
  version: latest
- name: ssl
  version: latest
